name: Weekday Auto Copy and Rename Template File (KST Time)

on:
  schedule:
    - cron: "15 15 * * 0-4"  # Runs at 00:00 KST (midnight) on Monday to Friday
  workflow_dispatch:  # Allows manual triggering

jobs:
  copy_and_rename_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy and rename template file into respective month folder
        run: |
          DATE=$(date +"%Y-%m-%d")  # Format: YYYY-MM-DD
          MONTH_NUM=$(date +"%m")  # Extract two-digit month (e.g., "02")
          MONTH_SHORT=$(date +"%b")  # Extract three-letter month (e.g., "Feb")
          MONTH_FOLDER="${MONTH_NUM}-${MONTH_SHORT}"  # Format as "02-Feb"

          # Stop creating files from August (08) onward
          if [ "$MONTH_NUM" -ge 08 ]; then
            echo "Skipping file creation since month is after July ($MONTH_FOLDER)."
            exit 0
          fi

          # Ensure the folder exists
          mkdir -p "$MONTH_FOLDER"

          # Copy the template.md file into the correct month folder
          cp template.md "$MONTH_FOLDER/${DATE}.md"

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Force Git to track ignored files
          git add -f "$MONTH_FOLDER/${DATE}.md"

          git commit -m "Auto-copied template.md to ${MONTH_FOLDER}/${DATE}.md"
          git push https://x-access-token:${GH_PAT}@github.com/100-hours-a-week/lillian-til HEAD:main

