name: Weekday Auto Copy and Rename Template File (KST Time)

on:
  schedule:
    - cron: "15 15 * * 0-4"  # Runs at 00:00 KST (midnight) on Monday to Friday
  workflow_dispatch:  # Allows manual triggering

jobs:
  copy_and_rename_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug print working directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Repository contents:"
          ls -R

      - name: Set date and folder variables
        run: |
          DATE=$(date +"%Y-%m-%d")  # Example: 2025-02-06
          MONTH_NUM=$(date +"%m")   # Example: 02
          MONTH_SHORT=$(date +"%b") # Example: Feb
          MONTH_FOLDER="${MONTH_NUM}-${MONTH_SHORT}"  # Example: 02-Feb

          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "MONTH_FOLDER=$MONTH_FOLDER" >> $GITHUB_ENV

          echo "DATE: $DATE"
          echo "MONTH_FOLDER: $MONTH_FOLDER"

      - name: Ensure correct working directory
        run: |
          cd /home/runner/work/lillian-til/lillian-til || exit 1
          echo "Switched to correct directory:"
          pwd

      - name: Create and verify month folder
        run: |
          mkdir -p "$MONTH_FOLDER"
          echo "Created folder: $MONTH_FOLDER"
          ls -la "$MONTH_FOLDER"

      - name: Copy and rename template file
        run: |
          if [ -f "template.md" ]; then
            cp template.md "$MONTH_FOLDER/${DATE}.md"
            echo "Copied template.md to $MONTH_FOLDER/${DATE}.md"
          else
            echo "Error: template.md not found!"
            exit 1
          fi

      - name: Verify file creation
        run: |
          echo "Checking if file exists in $MONTH_FOLDER ..."
          ls -la "$MONTH_FOLDER"
          cat "$MONTH_FOLDER/${DATE}.md" || echo "File not found!"

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd /home/runner/work/lillian-til/lillian-til  # Ensure correct directory

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if [ -f "$MONTH_FOLDER/${DATE}.md" ]; then
            git add -f "$MONTH_FOLDER/${DATE}.md"
            git commit -m "Auto-copied template.md to ${MONTH_FOLDER}/${DATE}.md"
            git push https://x-access-token:${GH_PAT}@github.com/100-hours-a-week/lillian-til.git HEAD:main
          else
            echo "Error: File $MONTH_FOLDER/${DATE}.md does not exist!"
            exit 1
          fi
